require "config.lazy"
require "config.colorschemes"
require "config.options"
require "config.keymaps"
require "config.autocmd"
require "config.debug"
require "config.notify"
require "config.transparent"
