vim.cmd("colorscheme tokyonight-storm")
-- require("themery").setup({
--     themes = {
--         {
--             name = "Tokyonight",
--             colorscheme = "tokyonight-storm"
--         },
--         {
--             name = "Gruvbox",
--             colorscheme = "gruvbox-material",
--             before = [[
--         -- vim.opt.background = "light"
--       ]]
--         },
--         {
--             name = "Aurora",
--             colorscheme = "aurora"
--         },
--         {
--             name = "Darkplus",
--             colorscheme = "darkplus"
--         },
--         {
--             name = "Dragon",
--             colorscheme = "kanagawa-dragon"
--
--         },
--         {
--             name = "Water",
--             colorscheme = "kanagawa-water",
--         },
--     }
-- })
